#+-- Plugin RP par stan1712 (stan1712.fr) --+
#+-- Traducteurs : stan1712 (French) | stan1712 (English) | legaming04 (Italian) | Starsaaa (Chinese) | ErHak_ (German) --+

#Version du plugin, il ne faut pas la changer !
Version: "Version 3.9.7"

#Modifiez le prefix ici
Prefix: "SeriousRP"

#Messages affichés lors du /seriousrp help
HelpMsg:
  DSrtp: "Pouvoir se teleporter aleatoirement"
  DTown: "Permet de se teleporter a la ville"
  DTownSet: "Permet de definir le point de spawn de la ville"
  DPhone: "Affiche le menu du telephone"
  
  DHelp: "Affiche l'aide"
  DVersion: "Connaitre la version du plugin"
  
#Modules du plugin
NoModule: "Le module n'est pas actif."
DeathItems: true
TownSystem: true

#Menu du téléphone
Phone:
  LorePhone1: "&9Voici votre telephone"
  LorePhone2: "&9Clic droit pour l'ouvrir"
  LorePhone3: "&6Proprietaire :"

  Answer: "&cBientot..."
  HangUp: "&cBientot..."
  Shutdown: "&cEteindre"
  
  You: "&aOui, c'est vous, vous etes beau non ?"
  Music: "&cBientot..."

  GoToTown: "&aDirection : Ville"
  YourNumber: "&cBientot..."

#Différents messages du plugin
Teleports:
  GoToTown: "Vous avez ete teleporte dans la ville"
  SetTown: "Vous avez set le spawn de la ville"
  TownWhere: "Le spawn de la ville se trouve en :"

RandomTeleport: "Teleportation a des milliers de blocs !"

Help: "Besoin d'aide ? Tapez /seriousrp help"
VersionHelp: "Version du plugin ? Tapez /seriousrp version"

Locations:
  Town:
    x: 0
    y: 0
    z: 0
    WorldName: world