#+-- Plugin RP by stan1712 (stan1712.fr) --+
#+-- Traductors : stan1712 (French) | stan1712 (English) | legaming04 (Italian) | Starsaaa (Chinese) | ErHak_ (German) --+

#Version of the plugin, do not change it !
Version: "Version 3.9.7"

#Modify your prefix here
Prefix: "SeriousRP"

#Display messages for the help menu
HelpMsg:
  Dsrtp: "In der Lage sein, zufällig teleportieren zu können"
  DTown: "Erlaubt, in die Stadt zu teleportieren"
  DTownSet: "Ermöglicht es Ihnen, den Spawnpunkt der Stadt festzulegen"
  DPhone: "Shows the phone GUI"
  
  DHelp: "Zeigt Hilfe an"
  DVersion: "Kennen Sie die Version des Plugins"
  
#SeriousRP modules
NoModule: "The module is offline."
DeathItems: true
TownSystem: true

#Phone Menu
Phone:
  LorePhone1: "&9Here is your phone"
  LorePhone2: "&9Right click to open it"
  LorePhone3: "&6Owner :"

  Answer: "&cSoon..."
  HangUp: "&cSoon..."
  Shutdown: "&cSwitch Off"
  
  You: "&aYes, this is you, you are beautiful isn't it ?"
  Music: "&cSoon..."

  GoToTown: "&aDirection : Town"
  YourNumber: "&cSoon..."

#Differents messages of the plugin
Teleports:
  GoToTown: "Du wurdest in der Stadt teleportiert"
  SetTown: "Du hast den Spawnpunkt der Stadt definiert"
  TownWhere: "Der Spawnpunkt der Stadt ist in :"

RandomTeleport: "Teleportation zu Tausenden von Blöcken !"

Help: "Besoin d'aide ? Tapez /seriousrp help"
VersionHelp: "Version du plugin ? Tapez /seriousrp version"

Locations:
  Town:
    x: 0
    y: 0
    z: 0
    WorldName: world