#+-- Plugin RP par stan1712 (stan1712.fr) --+
#+-- Traducteurs : stan1712 (French) | stan1712 (English) | legaming04 (Italian) | Starsaaa (Chinese) | ErHak_ (German) --+

#Version du plugin, il ne faut pas la changer !
Version: "Version 3.9.8-0.3b"

#Modifiez le prefix ici
Prefix: "SeriousRP"

#Messages affichés lors du /seriousrp help
HelpMsg:
  Dsrtp: "Pouvoir se teleporter aleatoirement"
  DTown: "Permet de se teleporter a la ville"
  DTownSet: "Permet de definir le point de spawn de la ville"
  DPhone: "Affiche le menu du telephone"
  
  DRevive: "Permet de réanimer un joueur"
  DMedInfo: "Permet de connaître les statistiques d'un joueur"
  
  DHelp: "Affiche l'aide"
  DVersion: "Connaitre la version du plugin"
  
#Modules du plugin
NoModule: "Le module n'est pas actif."
RPDeath: false
Medics: true
TownSystem: true

#Messages des medics
Medic:
  Revive: "&aVous avez bien reanime le joueur"
  Error: "&cn'est pas en ligne ou vous avez mal orthographie son pseudo !"
  NoNeed: "&cLe joueur n'a pas besoin de se faire réanimer"
MedInfo:
  Health: "Vie :"
  Hearts: "coeurs"
  Food: "Nourriture :"
  Coordinates: "est en :"

#Menu du téléphone
Phone:
  LorePhone1: "&9Voici votre telephone"
  LorePhone2: "&9Clic droit pour l'ouvrir"
  LorePhone3: "&6Proprietaire :"

  Answer: "&cBientot..."
  HangUp: "&cBientot..."
  Shutdown: "&cEteindre"
  
  You: "&aOui, c'est vous, vous etes beau non ?"
  Music: "&cBientot..."

  GoToTown: "&aDirection : Ville"
  YourNumber: "&cBientot..."

#Différents messages du plugin
Teleports:
  GoToTown: "Vous avez ete teleporte dans la ville"
  SetTown: "Vous avez set le spawn de la ville"
  TownWhere: "Le spawn de la ville se trouve en :"

RandomTeleport: "Teleportation a des milliers de blocs !"

Help: "Besoin d'aide ? Tapez /seriousrp help"
VersionHelp: "Version du plugin ? Tapez /seriousrp version"

NoPerms: "Vous n'avez pas la permission !"

Locations:
  Town:
    x: 0
    y: 0
    z: 0
    WorldName: world