name: SeriousRP
version: 3.9.7
author: stan1712
main: fr.stan1712.srp.srp
commands:
 seriousrp:
  description: Show the main menu
  permission: seriousrp.info
 version:
  description: Shows the version of the plugin
  permission: seriousrp.info
 help:
  description: Shows the help page
  permission: seriousrp.info
 srtp:
  description: Teleports you randomly in a radius of 10000 blocks
  permission: seriousrp.random
 srtown:
  description: Teleports you to the town
  permission: seriousrp.tptown
 chat:
  description: Blablabla
  permission: seriousrp.chat
 mobile:
  description: Allow you to give a phone
  permission: seriousrp.givephone